apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: apache
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - node1            
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent